package com.project.back_end.models;


import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import com.fasterxml.jackson.annotation.JsonProperty;

@Entity
@Table(name = "admin") // References the 'admin' SQL table
public class Admin {

    //    - Description: 
    //      - Represents the unique identifier for the Admin entity.
    //      - This field is auto-generated by the database using @GeneratedValue with strategy GenerationType.IDENTITY.
    //      - It is the primary key of the entity, identified by @Id annotation.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; //

    //    - Description: 
    //      - Represents the username of the admin.
    //      - Used to log into the system.
    //      - @NotNull validation ensures that this field cannot be null when creating or updating an Admin.
    @NotNull(message = "Username is required")
    @Column(unique = true)
    private String username;


    //    - Description: 
    //      - Represents the password of the admin for authentication.
    //      - The field is marked with @JsonProperty(access = JsonProperty.Access.WRITE_ONLY) to prevent the password from being exposed in JSON responses.
    //      - @NotNull validation ensures the password cannot be null when creating or updating an Admin.
    @NotNull(message = "Password is required")
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY) // Hides password in JSON response
    private String password; //

    // Constructors
    public Admin() {}

    public Admin(String username, String password) {
        this.username = username;
        this.password = password;
    }

    // Getters and Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getUsername() { return username; }
    public void setUsername(String username) { this.username = username; }

    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }
}

